---
- hosts: "{{ variable_host }}"
  become: true
  become_method: sudo
  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no

    - name: sshport
      prompt: What is your ssh port (if neaded)?
      private: no

    - name: knockphrase
      prompt: What is your knock phrase (if neaded)?
      private: no

  roles:
    - docker
    - firewall
    - general
    - knock
    - ssh
    - tmux
    - vim
    - zsh
