- hosts: "{{ variable_host }}"
# "You have to add the --extra-vars='variable_host='"
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: 'latest'
      update_cache: 'yes'
    vars:
      packages:
      - gnupg
      - software-properties-common
      - locales
      - language-pack-de
      - dbus
      - apt-transport-https
      - ca-certificates

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Add certbot Repository
    apt_repository:
      repo: ppa:certbot/certbot

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: 'latest'
      update_cache: 'yes'
    vars:
      packages:
      - certbot
      - python-certbot-apache
      - docker-ce
      - vim
      - git
      - nginx
      - mc
      - zsh
      - libpam-google-authenticator
      - curl

  - name: Ensure docker-compose is installed and available
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.0-rc2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Add the user 'lbejiuk'
    user:
      name: lbejiuk

  - name: change root's shel
    user:
      name: root
      shell: /bin/zsh

  - name: clone oh-my-zsh
    # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
    command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh'

  - name: Create autoload folder
    file:
      path: ~/.vim/autoload
      state: directory
      mode: '0755'

  - name: Create colors folder
    file:
      path: ~/.vim/colors
      state: directory
      mode: '0755'

  - name: clone Plug for vim
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.vim/autoload/plug.vim

  - name: clone Theme for vim
    get_url:
      url: https://raw.githubusercontent.com/kristijanhusak/vim-hybrid-material/master/colors/hybrid_reverse.vim
      dest: ~/.vim/colors/hybrid_reverse.vim

  - name: write .zshrc for root
    template:
      src: zshrc.j2
      dest: '~/.zshrc'
      backup: yes
      mode: 'u=rw,go=r'

  - name: Copy sshd_config from master to slave
    copy: src=files/sshd_config dest=/etc/ssh/sshd_config
  - name: Copy sshd from master to slave
    copy: src=files/sshd dest=/etc/pam.d/sshd
  - name: Copy sshd from master to slave
    copy: src=files/.vimrc dest=~/.vimrc

  - name: Set timezone to Europe/Berlin
    timezone:
      name: Europe/Berlin

  - name: Ensure the locale exists
    locale_gen:
      name: de_DE.UTF-8
  - name: set as default locale
    command: localectl set-locale LANG=de_DE.UTF-8
