---
- name: install google 2fa
  package:
    name: libpam-google-authenticator
    state: present
  tags: ['ssh']

- name: Copy config
  template:
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    backup: yes
    mode: 'u=rw,go=r'
  tags: ["ssh"]

- name: Copy config
  copy:
    src: files/sshd
    dest: "/etc/pam.d/sshd"
  tags: ["ssh"]

- name: ensure ~/.config/systemd/user is dir
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  tags: ["ssh"]

- name: Copy authorized_keys
  copy:
    src: files/authorized_keys
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: ["ssh"]
