---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: [ "docker" ]

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  tags: [ "docker" ]

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: 'latest'
    update_cache: 'yes'
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - certbot
  tags: [ "docker" ]

- name: Ensure docker-compose is installed and available
  get_url:
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
